# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='password',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default=123456, max_length=30),
            preserve_default=False,
        ),
    ]
